- name: Install/customize grafana
  debug: msg="Install/customize grafana"

- name: Create grafana directory on remote
  file: path=/home/{{ actinguser }}/etc/mars/grafana state=directory
  become: yes

- name: Download grafana binary tar.gz
  get_url: url="https://grafanarel.s3.amazonaws.com/builds/grafana-3.0.4-1464167696.linux-x64.tar.gz" dest=/home/{{ actinguser }}/tmp/grafana.tar.gz
  become: yes

- name: Uncompress grafana tar.gz
  command: tar -xf /home/{{ actinguser }}/tmp/grafana.tar.gz -C /home/{{ actinguser }}/app
  become: yes

- name: Rename grafana-with-version to grafana
  command: creates="/home/{{ actinguser }}/app/grafana" mv /home/{{ actinguser }}/app/grafana-3.0.4-1464167696 /home/{{ actinguser }}/app/grafana
  become: yes

- name: Move grafana defaults.ini to $HOME/etc/mars/grafana directory
  command: creates="/home/{{ actinguser }}/etc/mars/grafana/defaults.ini" mv /home/{{ actinguser }}/app/grafana/conf/defaults.ini /home/{{ actinguser }}/etc/mars/grafana/defaults.ini
  become: yes

- name: Create defaults.ini symlink
  file: src=/home/{{ actinguser }}/etc/mars/grafana/defaults.ini dest=/home/{{ actinguser }}/app/grafana/conf/defaults.ini state=link
  become: yes

- name: Costumize defaults.ini
  lineinfile: dest=/home/{{ actinguser }}/etc/mars/grafana/defaults.ini regexp='^http_port = ' line='http_port = 9700'
  become: yes

- name: Start grafana
  command: daemon -n grafana -r -- /home/{{ actinguser }}/app/grafana/bin/grafana-server -homepath /home/{{ actinguser }}/app/grafana -pidfile /home/{{ actinguser }}/var/run/grafana.pid
