---
language: python  # Needed to run ansible

python:
  - "2.7"

install:
  - pip install ansible

script:
- find . -maxdepth 1 -type f -name '*.yml' -not -name '.*' -not -name 'main.yml' | xargs -t -n1 ansible-playbook --extra-vars "servers=one,server=shinken,mgntnode=shinken,mgmtip=192.168.122.92" --syntax-check -i hosts.ini
