---
- hosts: '{{ servers }}'
  gather_facts: yes
  remote_user: admin
  vars:
    corpPath: '{{ lookup( "pipe", "pwd" ) | regex_replace( "^(.*)/ansible/pbs/.*", "\1/com/naviextras" ) }}'
    nodeColoc: '{{ group_names[0] }}'
    mgmtnode: '{{ mgmtnode }}'
    actinguser: 'admin'
  roles:
    - gatherssh
