---
- hosts: '{{ server }}'
  gather_facts: yes
  remote_user: root
  vars_files:
    - 'env.yml'
  become_user: '{{ actinguser }}'
  vars:
    nodeColoc: '{{ group_names[0] }}'

  roles:
    - { role: common }
    - { role: graphite, when: graphiteExist.stat.exists == False }
    - { role: shinken, when: shinkenExist.stat.exists == False }
    - { role: grafana, when: grafanaExist.stat.exists == False }
    - { role: thruk, when: thrukExist.stat.exists == False }
