---
- hosts: '{{ server }}'
  gather_facts: yes
  remote_user: root
  become_user: admin
  vars_files:
    - 'env.yml'
  vars:
    corpPath: '{{ lookup( "pipe", "pwd" ) | regex_replace( "^(.*)/ansible/pbs/.*", "\1/hu/linuxsysadmin" ) }}'
    nodeColoc: '{{ group_names[0] }}'

  roles:
    - { role: common }
    - { role: graphite, when: graphiteExist.stat.exists == False }
    - { role: shinken, when: shinkenExist.stat.exists == False }
