---
- hosts: '{{ servers }}'
  gather_facts: yes
  remote_user: root
  vars_files:
    - 'env.yml'
  become_user: '{{ actinguser }}'
  vars:
    nodeColoc: '{{ group_names[0] }}'
    mgmtnode: '{{ mgmtnode }}'
  roles:
    - nrpeconfig
