- name: Install/customize shinken
  debug: msg="Install/customize shinken"

- name: Apt install packages
  apt: name='{{ item }}' state=present
  with_items:
    - python-pip
    - python-pycurl
    - python-cherrypy3
    - python-paramiko
- user: name=shinken system=yes createhome=no
- name: Pip install packages
  pip: name='{{ item }}'
  with_items:
    - bottle
    - shinken

- name: Create required directories in $HOME/app/shinken
  file: path=/home/{{ actinguser }}/app/shinken/{{ item }} state=directory
  with_items:
    - ./etc
    - ./usr
    - ./var/lib
    - ./var/log
    - ./var/run
  become: yes

- file: src=/usr/bin dest=/home/{{ actinguser }}/app/shinken/usr/bin state=link
  become: yes

- name: Create directories in local cfgCVS
  local_action: file path={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars/shinken state=directory
  tags:
    - cvsadd

- name: Copy and create required directories to $HOME
  command: creates=/home/{{ actinguser }}/app/shinken/etc/shinken cp -r /etc/shinken /home/{{ actinguser }}/app/shinken/etc/
  become: yes
- command: creates=/home/{{ actinguser }}/var/lib/shinken cp -r /var/lib/shinken /home/{{ actinguser }}/var/lib/
  become: yes
- command: creates=/home/{{ actinguser }}/var/log/shinken cp -r /var/log/shinken /home/{{ actinguser }}/var/log/
  become: yes
- command: creates=/home/{{ actinguser }}/var/run/shinken cp -r /var/run/shinken /home/{{ actinguser }}/var/run/
  become: yes

- name: Create symlinks to $HOME/var
  file: src=/home/{{ actinguser }}/var/{{ item }}/shinken dest=/home/{{ actinguser }}/app/shinken/var/{{ item }}/shinken state=link
  with_items:
    - lib
    - log
    - run
  become: yes

- name: Create shinken.ini from template
  template: src=shinken.ini.template dest=/home/{{ actinguser }}/etc/mars/shinken.ini
  become: yes
- file: src=/home/{{ actinguser }}/etc/mars/shinken.ini dest=/home/{{ actinguser }}/.shinken.ini state=link

- synchronize: src=/home/{{ actinguser }}/etc/mars/shinken.ini dest={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars/shinken.ini mode=pull
  tags:
    - cvsadd

- name: Init shinken and install modules
  command: shinken --init
  become: yes
- command: shinken install {{ item }}
  with_items:
    - ui-graphite
    - graphite
    - linux-ssh
    - auth-cfg-password
    - webui2
    - sqlitedb
    - livestatus
    - logstore-sqlite
  become: yes

- name: Create directory $HOME/etc/mars/shinken
  file: path='/home/{{ actinguser }}/etc/mars/shinken' state=directory
  become: yes

- name: Move ini files to $HOME/etc/mars/shinken
  command: creates=/home/{{ actinguser }}/etc/mars/shinken/daemons mv /home/{{ actinguser }}/app/shinken/etc/shinken/daemons /home/{{ actinguser }}/etc/mars/shinken/daemons
  become: yes

- name: Create required directories in local cfgCVS
  local_action: file path='{{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars/shinken/{{ item }}' state=directory
  with_items:
    - daemons
    - brokers
    - hosts
    - modules
    - resource.d
    - reactionners
    - pollers
    - schedulers
    - receivers
    - arbiters
  tags:
    - cvsadd

- name: Synchronize original ini files to local cfgCVS
  synchronize: src=/home/{{ actinguser }}/etc/mars/shinken/daemons dest={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars/shinken/ recursive=yes mode=pull
  tags:
    - cvsadd

- name: Find ini files
  find: path=/home/{{ actinguser }}/etc/mars/shinken/daemons patterns=*.ini recurse=yes
  register: iniFiles
  become: yes

- name: Modify ini files
  replace: dest='{{ item.path }}' regexp='=/var/' replace='=/home/{{ actinguser }}/app/shinken/var/'
  with_items: '{{ iniFiles.files }}'
  become: yes
- replace: dest='{{ item.path }}' regexp='= /var/' replace='= /home/{{ actinguser }}/app/shinken/var/'
  with_items: '{{ iniFiles.files }}'
  become: yes
- replace: dest='{{ item.path }}' regexp='=/usr/' replace='=/home/{{ actinguser }}/app/shinken/usr/'
  with_items: '{{ iniFiles.files }}'
  become: yes
- replace: dest='{{ item.path }}' regexp='=/etc/shinken/' replace='=/home/{{ actinguser }}/app/shinken/etc/shinken/'
  with_items: '{{ iniFiles.files }}'
  become: yes
- replace: dest='{{ item.path }}' regexp='=shinken' replace='={{ actinguser }}' backup=yes
  with_items: '{{ iniFiles.files }}'
  become: yes
- replace: dest='{{ item.path }}' regexp='port=77' replace='port={{ portbase }}'
  with_items: '{{ iniFiles.files }}'
  become: yes
- replace: dest='{{ item.path }}' regexp='# *port=' replace='port='
  with_items: '{{ iniFiles.files }}'
  become: yes

- lineinfile: dest={{ item.path }} regexp='user=' line='user={{ actinguser }}'
  with_items: '{{ iniFiles.files }}'
  become: yes
- lineinfile: dest={{ item.path }} regexp='group=' line='group={{ actinguser }}'
  with_items: '{{ iniFiles.files }}'
  become: yes

- name: Create symlinks to ini files
  file: path=/home/{{ actinguser }}/app/shinken/etc/shinken/daemons state=directory
  become: yes
- file: src={{ item.path }} dest=/home/{{ actinguser }}/app/shinken/etc/shinken/daemons/{{ item.path|basename() }} state=link
  with_items: '{{ iniFiles.files }}'
  become: yes

- name: Synchronize /etc/default/shinken
  synchronize: src=/etc/default/shinken dest={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/etc/default/ mode=pull
  tags:
    - cvsadd

- name: Modify /etc/default/shinken
  replace: dest=/etc/default/shinken regexp='=/etc/' replace='=/home/{{ actinguser }}/app/shinken/etc/'
- replace: dest=/etc/default/shinken regexp='=/usr/' replace='=/home/{{ actinguser }}/app/shinken/usr/'
- replace: dest=/etc/default/shinken regexp='=/var/' replace='=/home/{{ actinguser }}/app/shinken/var/'
- replace: dest=/etc/default/shinken regexp='=shinken' replace='={{ actinguser }}'


- name: Find cfg files to modify
  find: path=/home/{{ actinguser }}/app/shinken/etc/shinken patterns=*.cfg contains='[ \t]*port[ \t]*' recurse=yes
  register: cfgFiles
  become: yes
- find: path=/home/{{ actinguser }}/app/shinken/etc/shinken patterns=*.cfg contains='.*=shinken' recurse=yes
  register: cfgUserFiles
  become: yes

- name: Create required directories in $HOME/etc/mars/shinken
  file: path='/home/{{ actinguser }}/etc/mars/shinken/{{ item }}' state=directory
  with_items:
    - brokers
    - hosts
    - modules
    - resource.d
    - reactionners
    - pollers
    - schedulers
    - receivers
    - arbiters
  become: yes

- name: Move related cfg files to $HOME/etc/mars/shinken
  command: creates=/home/{{ actinguser }}/etc/mars/shinken/{{ item.path.split('/')[7] }}/{{ item.path|basename() }} mv {{ item.path }} /home/{{ actinguser }}/etc/mars/shinken/{{ item.path.split('/')[7] }}/{{ item.path|basename() }}
  with_items: '{{ cfgFiles.files }}'
  when: item.path|basename != "shinken.cfg"
  become: yes
- command: creates=/home/{{ actinguser }}/etc/mars/shinken/{{ item.path.split('/')[7] }}/{{ item.path|basename() }} mv {{ item.path }} /home/{{ actinguser }}/etc/mars/shinken/{{ item.path.split('/')[7] }}/{{ item.path|basename() }}
  with_items: '{{ cfgUserFiles.files }}'
  when: item.path|basename != "shinken.cfg"
  become: yes
- command: creates=/home/{{ actinguser }}/etc/mars/shinken/{{ item.path|basename() }} mv {{ item.path }} /home/{{ actinguser }}/etc/mars/shinken/{{ item.path|basename() }}
  with_items: '{{ cfgUserFiles.files }}'
  when: item.path|basename == "shinken.cfg"
  become: yes

- find: path=/home/{{ actinguser }}/etc/mars/shinken patterns=*.cfg recurse=yes
  register: configFiles
  become: yes

- name: Create symlinks to cfg files
  file: src={{ item.path }} dest=/home/{{ actinguser }}/app/shinken/etc/shinken/{{ item.path.split('/')[6] }}/{{ item.path|basename() }} state=link
  with_items: '{{ configFiles.files }}'
  when: item.path|basename != "shinken.cfg"
  become: yes
- file: src={{ item.path }} dest=/home/{{ actinguser }}/app/shinken/etc/shinken/{{ item.path|basename() }} state=link
  with_items: '{{ configFiles.files }}'
  when: item.path|basename == "shinken.cfg"
  become: yes

- name: Synchronize cfg files to local cfgCVS
  synchronize: src={{ item.path }} dest={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/{{ item.path }} mode=pull
  with_items: '{{ configFiles.files }}'
  tags:
    - cvsadd

- name: Move specified config files to $HOME/etc/mars/shinken
  command: creates=/home/{{ actinguser }}/etc/mars/shinken/{{ item }} mv /home/{{ actinguser }}/app/shinken/etc/shinken/{{ item }} /home/{{ actinguser }}/etc/mars/shinken/{{ item }}
  with_items:
    - resource.d/paths.cfg
    - shinken.cfg
    - brokers/broker-master.cfg
    - hosts/localhost.cfg
    - modules/webui2.cfg
    - modules/graphite.cfg
    - modules/livestatus.cfg
    - modules/ui-graphite.cfg

- name: Create symlink to specified config files
  file: src=/home/{{ actinguser }}/etc/mars/shinken/{{ item }} dest=/home/{{ actinguser }}/app/shinken/etc/shinken/{{ item }} state=link
  with_items:
    - resource.d/paths.cfg
    - shinken.cfg
    - brokers/broker-master.cfg
    - hosts/localhost.cfg
    - modules/webui2.cfg
    - modules/graphite.cfg
    - modules/livestatus.cfg
    - modules/ui-graphite.cfg

- name: Symchronize specified config files to local cfgCVS
  synchronize: src=/home/{{ actinguser }}/etc/mars/shinken/{{ item }} dest={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars/shinken/{{ item }} mode=pull
  with_items:
    - resource.d/paths.cfg
    - shinken.cfg
    - brokers/broker-master.cfg
    - hosts/localhost.cfg
    - modules/webui2.cfg
    - modules/graphite.cfg
    - modules/livestatus.cfg
    - modules/ui-graphite.cfg
  tags:
    - cvsadd

- name: Modify cfg files
  replace: dest={{ item.path }} regexp='port *77' replace='port {{ portbase }}'
  with_items: '{{ configFiles.files }}'
  become: yes

- replace: dest=/home/{{ actinguser }}/etc/mars/shinken/resource.d/paths.cfg regexp='=/usr/lib/' replace='=/home/{{ actinguser }}/app/shinken/usr/lib/'
  become: yes
- replace: dest=/home/{{ actinguser }}/etc/mars/shinken/resource.d/paths.cfg regexp='=/var/lib/' replace='=/home/{{ actinguser }}/app/shinken/var/lib/'
  become: yes
- replace: dest=/home/{{ actinguser }}/etc/mars/shinken/shinken.cfg regexp='=/var/' replace='=/home/{{ actinguser }}/app/shinken/var/' backup=yes
  become: yes
- replace: dest=/home/{{ actinguser }}/etc/mars/shinken/shinken.cfg regexp='=/etc/' replace='=/home/{{ actinguser }}/app/shinken/etc/' backup=yes
  become: yes

- replace: dest={{ item.path }} regexp='=shinken' replace='={{ actinguser }}'
  with_items: '{{ configFiles.files }}'
  become: yes

- replace: dest=/home/{{ actinguser }}/etc/mars/shinken/brokers/broker-master.cfg regexp='^([ \t]*modules[ \t]*)$' replace='\1 webui2,graphite,livestatus'
  become: yes
- replace: dest=/home/{{ actinguser }}/etc/mars/shinken/hosts/localhost.cfg regexp='^([ \t]*use[ \t]+)(generic-host)$' replace='\1linux-ssh,\2'
  become: yes
- template: src=webui2.conf.template dest=/home/{{ actinguser }}/etc/mars/shinken/modules/webui2.cfg
  become: yes
- replace: dest=/home/{{ actinguser }}/etc/mars/shinken/modules/graphite.cfg regexp='port *20' replace='port {{ portbase }}'
  become: yes
- replace: dest=/home/{{ actinguser }}/etc/mars/shinken/modules/livestatus.cfg regexp='port *50000' replace='port {{ portbase }}50'
  become: yes
- replace: dest=/home/{{ actinguser }}/etc/mars/shinken/modules/ui-graphite.cfg regexp='uri *http://YOURSERVERNAME/' replace='uri http://localhost:{{ portbase }}80'
  become: yes
- replace: dest=/home/{{ actinguser }}/etc/mars/shinken/modules/ui-graphite.cfg regexp='templates_path[ \t]*/var/' replace='templates_path /home/{{ actinguser }}/shinken/var/'
  become: yes

- name: Add and commit original files to CVS
  local_action: shell chdir={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars cvs add shinken
  tags:
    - cvscommit
    - cvsadd

- local_action: shell chdir={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars/shinken/ cvs add {{ item }}
  with_items:
    - daemons
    - brokers
    - hosts
    - modules
    - resource.d
    - reactionners
    - pollers
    - schedulers
    - receivers
    - arbiters
  tags:
    - cvscommit
    - cvsadd

- local_action: shell chdir={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars/shinken find . \( -type d -name CVS -prune \) -o \( -type f -exec cvs add '{}' \; \)
  tags:
    - cvscommit
    - cvsadd

- local_action: |
    shell chdir={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars/shinken cvs commit -m "Ansible shinken/mars
    Initial commit"
  tags:
    - cvscommit

- local_action: shell chdir={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }} cvs add {{ item }}
  with_items:
    - ./etc/default/shinken
  tags:
    - cvscommit
    - cvsadd
  ignore_errors: yes

- local_action: |
    shell chdir={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }} cvs commit -m "Ansible shinken/mars
    Initial commit" ./etc/default/shinken
  tags:
    - cvscommit

- name: Synchronize modified files to local cfgCVS
  synchronize: src={{ item.path }} dest={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/{{ item.path }} mode=pull
  with_items: '{{ configFiles.files }}'
  tags:
    - cvsadd

- synchronize: src=/home/{{ actinguser }}/etc/mars/shinken/{{ item }} dest={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars/shinken/{{ item }} mode=pull
  with_items:
    - resource.d/paths.cfg
    - shinken.cfg
    - brokers/broker-master.cfg
    - hosts/localhost.cfg
    - modules/webui2.cfg
    - modules/graphite.cfg
    - modules/livestatus.cfg
    - modules/ui-graphite.cfg
  tags:
    - cvsadd

- synchronize: src=/etc/default/shinken dest={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/etc/default/ mode=pull
  tags:
    - cvsadd

- name: Commit modified files to CVS
  local_action: |
    shell chdir={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }}/home/{{ actinguser }}/etc/mars/shinken cvs commit -m "Ansible shinken/mars
    Second commit"
  tags:
    - cvscommit
    - overwrite

- local_action: |
    shell chdir={{ corpPath }}/{{ nodeColoc }}/{{ ansible_nodename }} cvs commit -m "Ansible shinken/mars
    Second commit" ./etc/default/shinken
  tags:
    - cvscommit
    - overwrite
