---
- debug: var=ansible_nodename
- debug: var=nodeColoc
- debug: var=actinguser
- debug: var=corpPath
- apt: update_cache=yes

- name: Create mars dirs
  debug: msg="Create mars dirs"
- file: path=/home/{{ actinguser }}/app state=directory
  become: yes
- file: path=/home/{{ actinguser }}/etc/mars state=directory
  become: yes

- file: path=/home/{{ actinguser }}/var/{{ item }} state=directory
  with_items:
    - log
    - run
    - lib
  become: yes

- stat: path=/home/{{ actinguser }}/app/graphite
  register: graphiteExist

- stat: path=/home/{{ actinguser }}/app/shinken
  register: shinkenExist

- stat: path=/home/{{ actinguser }}/app/thruk
  register: thrukExist

- stat: path=/home/{{ actinguser }}/app/grafana
  register: grafanaExist

